# BetterAuth configuration - Use App entities
services:
    BetterAuth\Symfony\Storage\Doctrine\DoctrineUserRepository:
        arguments:
            $userClass: 'App\Entity\User'

    BetterAuth\Symfony\Storage\Doctrine\DoctrineSessionRepository:
        arguments:
            $sessionClass: 'App\Entity\Session'

    BetterAuth\Symfony\Storage\Doctrine\DoctrineRefreshTokenRepository:
        arguments:
            $refreshTokenClass: 'App\Entity\RefreshToken'

    BetterAuth\Symfony\Storage\Doctrine\DoctrineGuestSessionRepository: ~

    BetterAuth\Providers\GuestSessionProvider\GuestSessionProvider:
        arguments:
            $sessionLifetime: 86400  # 24 hours
